inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

require: rubocop-rspec

# module name is `ChatWork`, but I want to use `chatwork` as filename
RSpec/FilePath:
  Enabled: false
