inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

require: rubocop-rspec

AllCops:
  Exclude:
    - 'gemfiles/vendor/**/*'

    # c.f. https://github.com/rubocop-hq/rubocop/blob/v0.79.0/config/default.yml#L60-L64
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

# module name is `ChatWork`, but I want to use `chatwork` as filename
RSpec/FilePath:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
