sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install:
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - RUBYOPT=$RSPEC_RUBYOPT bundle exec rake spec
  - bundle exec rubocop
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.6
      env: RSPEC_RUBYOPT="--jit"
    - rvm: 2.7
      env: RSPEC_RUBYOPT="--jit"
    - rvm: ruby-head
      env: RSPEC_RUBYOPT="--jit"
env:
  global:
    secure: Ntdheemdu1GavPR/3kPfQg1tR13FTP0jE9KxsSKcG32VbIzM69l22OXXwYttFexMhA1dMNytv5bKGIszeiO+YjwzDXkcDHF7ZULc24epsGCOVfNax4g47Q+Lgt2kpAsx8V/8/SIpK7VeBhc2nPvhAKPjTZ8ddN2gLHk4wifLRFA=
