sudo: false
language: ruby
rvm:
- 2.2
- 2.3
- 2.4.1
- ruby-head
bundler_args: "--jobs=2"
cache: bundler
before_install: gem install bundler -v 1.16.0
script:
- bundle exec rake spec
branches:
  only:
  - master
matrix:
  allow_failures:
  - rvm: ruby-head
