name: test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)

env:
  RUBYOPT: -EUTF-8

jobs:
  test:
    runs-on: ubuntu-latest

    container: ${{ matrix.ruby }}

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - ruby:2.4
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
          - rubylang/ruby:master-nightly-bionic
        gemfile:
          - faraday_0
          - faraday_1
        include:
          - ruby: rubylang/ruby:master-nightly-bionic
            allow_failures: "true"

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Cache vendor/bundle
        uses: actions/cache@v1
        id: cache_gem
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ matrix.ruby }}-${{ github.sha }}
          restore-keys: |
            v1-gem-${{ runner.os }}-${{ matrix.ruby }}-
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: bundle update
        run: |
          set -xe
          bundle config path vendor/bundle
          bundle update --jobs $(nproc) --retry 3
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - run: bundle exec rspec
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
          parallel: true

      - run: bundle exec rubocop
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
        if: matrix.ruby < 'ruby:3.0' # FIXME: remove this after upgrade rubocop

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
